### ISSUE TITLE
大大的离谱bug

### ISSUE THREAD

**Issue by zhiziqixingdeng** [NIHAOAWA/NIHAO_Useful_Tools#1]
bug，int user后面要加;,这是不是连编译都没有编译

**Comment by zhiziqixingdeng** [comment]
> bug，int user后面要加;,这是不是连编译都没有编译

而且，如果真要做复读机的话，要把int user;换成string user;,ok?

**Comment by NIHAOAWA** [comment]
OKOK，感谢🙏

**Comment by zhiziqixingdeng** [comment]
加上#include <string>,然后把cin>>user换成getline(cin,user);,好吗?

**Comment by zhiziqixingdeng** [comment]
加上#include <string>,然后把cin>>user换成getline(cin,user);,好吗?

**Comment by zhiziqixingdeng** [comment]
加上#include <string>,然后把cin>>user换成getline(cin,user);,好吗?

**Comment by zhiziqixingdeng** [comment]
加上#include <string>,然后把cin>>user换成getline(cin,user);,好吗?

**Comment by zhiziqixingdeng** [comment]
加上#include <string>,然后把cin>>user换成getline(cin,user);,好吗?

**Comment by NIHAOAWA** [comment]
最近我没时间写代码，等我有时间再来写

**Comment by zhiziqixingdeng** [comment]
6
